title: Tareian Cazares, PhD Candidate
description: I am using this site to document my thesis research, the things I learn, and projects I am working on. 
remote_theme: "mmistakes/jekyll-theme-basically-basic@1.4.5
markdown:    kramdown
